const Category = {
  MOVIE: process.env.REACT_APP_CATID_MOVIE,
  TV: process.env.REACT_APP_CATID_TV,
  GAME: process.env.REACT_APP_CATID_VG,
  TEXTBOOK: process.env.REACT_APP_CATID_TEXTBOOK,
  SCHOOL: process.env.REACT_APP_CATID_SCHOOL,
  CLASS: process.env.REACT_APP_CATID_CLASS,
  ONLINE_LEARNING: process.env.REACT_APP_CATID_OL,
  ONLINE_RESOURCE: process.env.REACT_APP_CATID_OR,
  ARTICLE: process.env.REACT_APP_CATID_ARTICLES,
  POLITICAL_POLICY: process.env.REACT_APP_CATID_POLITICAL_POLICY,
  MISDISINFO: process.env.REACT_APP_CATID_MISDIS,
  JOB_PROSPECT: process.env.REACT_APP_CATID_JP,
  APPLICATION_PROCESS: process.env.REACT_APP_CATID_AP,
  MENTAL_HEALTH: process.env.REACT_APP_CATID_MENTALHEALTH,
  BEVERAGE: process.env.REACT_APP_CATID_BEV
};

module.exports = Category;